use std::{
    env,
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
};

use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::{Item, ItemImpl, Visibility};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let solutions_dir = src_dir.join("solutions");

    println!("cargo:rerun-if-changed={}", solutions_dir.display());

    // Collect src/solutions/*.rs excluding mod.rs
    let mut files: Vec<PathBuf> = vec![];
    if let Ok(rd) = fs::read_dir(&solutions_dir) {
        for ent in rd.flatten() {
            let p = ent.path();
            if p.is_dir() {
                continue;
            }
            if p.extension() != Some(OsStr::new("rs")) {
                continue;
            }
            if p.file_name() == Some(OsStr::new("mod.rs")) {
                continue;
            }
            println!("cargo:rerun-if-changed={}", p.display());
            files.push(p);
        }
    }
    files.sort();

    // Generate src/solutions/mod.rs
    let solutions_mod_rs = generate_solutions_mod_rs(&files);
    write_file(solutions_dir.join("mod.rs"), &solutions_mod_rs);

    // Generate src/registry.rs used by main
    let registry_rs = generate_registry_rs(&files, &solutions_dir);
    write_file(src_dir.join("registry.rs"), &registry_rs);
}

fn write_file(path: PathBuf, contents: &str) {
    let parent = path.parent().unwrap();
    fs::create_dir_all(parent).unwrap();

    // Only write if changed
    let write = match fs::read_to_string(&path) {
        Ok(existing) => existing != contents,
        Err(_) => true,
    };
    if write {
        fs::write(&path, contents).unwrap();
    }
}

fn generate_solutions_mod_rs(files: &[PathBuf]) -> String {
    let mut s = String::new();
    s.push_str("// @generated by build.rs — do not edit by hand.\n");
    s.push_str("#![allow(clippy::all)]\n\n");

    for f in files {
        let stem = f.file_stem().unwrap().to_string_lossy();
        s.push_str(&format!("pub mod {stem};\n"));
    }
    s
}

fn generate_registry_rs(files: &[PathBuf], solutions_dir: &Path) -> String {
    let mut entries: Vec<TokenStream2> = vec![];
    let mut wrappers: Vec<TokenStream2> = vec![];

    for f in files {
        let stem = f.file_stem().unwrap().to_string_lossy().to_string();
        let rel_file = Path::new("src")
            .join("solutions")
            .join(f.file_name().unwrap());
        let rel_file_str = rel_file.to_string_lossy().replace('\\', "/");

        let src = fs::read_to_string(f).unwrap_or_else(|e| {
            panic!("Failed to read {}: {e}", f.display());
        });

        let syn_file = syn::parse_file(&src).unwrap_or_else(|e| {
            panic!("Failed to parse {} as Rust source: {e}", f.display());
        });

        let (fn_name, fn_inputs, output_kind) = find_entry_fn(&syn_file)
            .unwrap_or_else(|| panic!("No `pub fn` found in `impl Solution` in {}", f.display()));

        let expected = fn_inputs.len();
        let expected_lit = syn::Index::from(expected);

        let mod_ident = format_ident!("{}", stem);
        let wrap_ident = format_ident!("__run_{}_{}", stem, fn_name);
        let fn_ident = format_ident!("{}", fn_name);

        let (arg_extracts, arg_idents): (Vec<_>, Vec<_>) = fn_inputs
            .iter()
            .enumerate()
            .map(|(i, ty)| {
                let arg_i = format_ident!("arg_{i}");
                let idx = syn::Index::from(i);

                let stmt = match infer_arg_codec(ty) {
                    ArgCodec::SerdeJson => quote! {
                        let #arg_i: #ty = serde_json::from_value(values[#idx].clone())
                            .map_err(|e| format!("arg {}: {}", #idx, e))?;
                    },
                    ArgCodec::ListNodeOptionBox => quote! {
                        let #arg_i: Option<Box<crate::prelude::ListNode>> =
                            crate::prelude::list_node_from_value(&values[#idx])
                                .map_err(|e| format!("arg {}: {}", #idx, e))?;
                    },
                };

                (stmt, arg_i)
            })
            .collect();

        let call_expr = match output_kind {
            OutputKind::Unit => quote! {
                {
                    let _p = crate::profiler::ProfileScope::new(stringify!(#fn_ident));
                    crate::solutions::#mod_ident::Solution::#fn_ident(#(#arg_idents),*);
                }
                Ok(())
            },
            OutputKind::Value(ValueCodec::SerdeJson) => quote! {
                let out = {
                    let _p = crate::profiler::ProfileScope::new(stringify!(#fn_ident));
                    crate::solutions::#mod_ident::Solution::#fn_ident(#(#arg_idents),*)
                };
                let s = serde_json::to_string_pretty(&out).map_err(|e| e.to_string())?;
                println!("Result: {s}");
                Ok(())
            },
            OutputKind::Value(ValueCodec::ListNodeOptionBox) => quote! {
                let out: Option<Box<crate::prelude::ListNode>> = {
                    let _p = crate::profiler::ProfileScope::new(stringify!(#fn_ident));
                    crate::solutions::#mod_ident::Solution::#fn_ident(#(#arg_idents),*)
                };
                let v = crate::prelude::list_node_to_value(&out);
                let s = serde_json::to_string_pretty(&v).map_err(|e| e.to_string())?;
                println!("Result: {s}");
                Ok(())
            },
        };

        wrappers.push(quote! {
            fn #wrap_ident(args: &[String]) {
                match (|| -> Result<(), String> {
                    let values: Vec<serde_json::Value> = parse_values(args)?;
                    if values.len() != #expected {
                        return Err(format!("Expected {} args, got {}", #expected_lit, values.len()));
                    }

                    #(#arg_extracts)*

                    #call_expr
                })() {
                    Ok(()) => {}
                    Err(e) => {
                        eprintln!("{e}");
                        eprintln!("Tip: pass args as JSON. Either one JSON array, or multiple JSON values.");
                        std::process::exit(2);
                    }
                }
            }
        });

        entries.push(quote! {
            Entry {
                name: #fn_name,
                file: #rel_file_str,
                run: #wrap_ident,
            }
        });
    }

    let generated = quote! {
        // @generated by build.rs — do not edit by hand.
        #![allow(clippy::all)]
        #![allow(dead_code)]
        #![allow(unused_imports)]
        #![allow(unused_variables)]

        pub struct Entry {
            pub name: &'static str,
            pub file: &'static str,
            pub run: fn(&[String]),
        }

        pub static SOLUTIONS: &[Entry] = &[
            #(#entries),*
        ];

        pub fn select_solution(key: &str) -> Result<&'static Entry, String> {
            let key = key.trim();
            if key.is_empty() {
                return Err("Empty selection.".to_string());
            }
            if let Ok(i) = key.parse::<usize>() {
                return SOLUTIONS.get(i).ok_or_else(|| format!("Index {i} out of range."));
            }
            for e in SOLUTIONS {
                if e.name == key {
                    return Ok(e);
                }
            }
            Err(format!("No entry named `{key}`. Use an index from the list."))
        }

        pub fn run_entry(entry: &Entry, args: &[String]) {
            (entry.run)(args)
        }

        fn parse_values(args: &[String]) -> Result<Vec<serde_json::Value>, String> {
            if args.is_empty() {
                return Ok(vec![]);
            }
            if args.len() == 1 {
                let a0 = args[0].trim();
                if a0.starts_with('[') {
                    let v: Vec<serde_json::Value> =
                        serde_json::from_str(a0).map_err(|e| e.to_string())?;
                    return Ok(v);
                }
            }
            let mut out = Vec::with_capacity(args.len());
            for (i, a) in args.iter().enumerate() {
                match serde_json::from_str::<serde_json::Value>(a) {
                    Ok(v) => out.push(v),
                    Err(_) => {
                        out.push(serde_json::Value::String(a.clone()))
                    }
                }
            }
            Ok(out)
        }

        #(#wrappers)*
    };

    // Pretty-print tokens into normal Rust source
    let file: syn::File = syn::parse2(generated).expect("generated registry did not parse");
    let pretty = prettyplease::unparse(&file);

    let mut s = String::new();
    s.push_str("// This file is generated into src/registry.rs for rust-analyzer friendliness.\n");
    s.push_str(&format!(
        "// Modules directory: {}\n\n",
        solutions_dir.display()
    ));
    s.push_str(&pretty);
    if !s.ends_with('\n') {
        s.push('\n');
    }
    s
}

#[derive(Clone, Copy, Debug)]
enum ArgCodec {
    SerdeJson,
    ListNodeOptionBox,
}

#[derive(Clone, Copy, Debug)]
enum ValueCodec {
    SerdeJson,
    ListNodeOptionBox,
}

#[derive(Clone, Copy, Debug)]
enum OutputKind {
    Unit,
    Value(ValueCodec),
}

fn find_entry_fn(syn_file: &syn::File) -> Option<(String, Vec<syn::Type>, OutputKind)> {
    for item in &syn_file.items {
        let Item::Impl(ItemImpl { self_ty, items, .. }) = item else {
            continue;
        };

        // Match `impl Solution { ... }`
        if let syn::Type::Path(tp) = &**self_ty
            && tp
                .path
                .segments
                .last()
                .map(|s| s.ident == "Solution")
                .unwrap_or(false)
        {
            for it in items {
                let syn::ImplItem::Fn(f) = it else { continue };
                if !matches!(f.vis, Visibility::Public(_)) {
                    continue;
                }

                let name = f.sig.ident.to_string();

                let mut inputs = vec![];
                for input in &f.sig.inputs {
                    match input {
                        syn::FnArg::Receiver(_) => {}
                        syn::FnArg::Typed(pat_ty) => inputs.push((*pat_ty.ty).clone()),
                    }
                }

                let output = infer_output_kind(&f.sig.output);
                return Some((name, inputs, output));
            }
        }
    }
    None
}

fn infer_arg_codec(ty: &syn::Type) -> ArgCodec {
    if is_listnode(ty) {
        ArgCodec::ListNodeOptionBox
    } else {
        ArgCodec::SerdeJson
    }
}

fn infer_output_kind(ret: &syn::ReturnType) -> OutputKind {
    match ret {
        syn::ReturnType::Default => OutputKind::Unit,
        syn::ReturnType::Type(_, ty) => {
            if is_listnode(ty) {
                OutputKind::Value(ValueCodec::ListNodeOptionBox)
            } else {
                OutputKind::Value(ValueCodec::SerdeJson)
            }
        }
    }
}

fn last_ident_is(path: &syn::Path, name: &str) -> bool {
    path.segments
        .last()
        .map(|s| s.ident == name)
        .unwrap_or(false)
}

fn is_listnode(ty: &syn::Type) -> bool {
    use syn::{GenericArgument, PathArguments, Type};

    let Type::Path(tp) = ty else { return false };
    let opt_seg = match tp.path.segments.last() {
        Some(s) if s.ident == "Option" => s,
        _ => return false,
    };

    let PathArguments::AngleBracketed(opt_args) = &opt_seg.arguments else {
        return false;
    };
    if opt_args.args.len() != 1 {
        return false;
    }

    let GenericArgument::Type(inner_ty) = opt_args.args.first().unwrap() else {
        return false;
    };
    let Type::Path(inner_tp) = inner_ty else {
        return false;
    };
    let box_seg = match inner_tp.path.segments.last() {
        Some(s) if s.ident == "Box" => s,
        _ => return false,
    };

    let PathArguments::AngleBracketed(box_args) = &box_seg.arguments else {
        return false;
    };
    if box_args.args.len() != 1 {
        return false;
    }

    let GenericArgument::Type(node_ty) = box_args.args.first().unwrap() else {
        return false;
    };
    let Type::Path(node_tp) = node_ty else {
        return false;
    };

    last_ident_is(&node_tp.path, "ListNode")
}
